app:
  smtp-username: foo
  smtp-password: secret
  jwt-secret-key: ^%A-Q#z-x*
  jwt-expiry-interval: 3600000
  public-endpoints:
    - /api/v1/auth/token
    - /api/docs
    - /api/swagger-ui
    - /api/swagger-ui/**
    - /api/monitoring
    - /monitoring
    - /api/webjars/swagger-ui
    - /api/webjars/swagger-ui/**
    - /docs/swagger-config
    - /actuator
    - /actuator/**
    - /api/actuator
    - /api/actuator/**
    - /favicon.ico

springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /api/swagger-ui

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include: info,health,metrics,beans,configprops,conditions,env,httptrace,mappings,threaddump,logfile

server:
  port: 8080
  compression:
    enabled: true
  http2:
    enabled: false
  ssl:
    enabled: true
    ciphers:
      - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
      - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
      - TLS_RSA_WITH_AES_128_GCM_SHA256
      - TLS_RSA_WITH_AES_128_CBC_SHA
      - TLS_RSA_WITH_AES_256_CBC_SHA
      - TLS_AES_128_GCM_SHA256
      - TLS_AES_256_GCM_SHA384
    protocol: TLS
    enabled-protocols:
      - TLSv1
      - TLSv1.1
      - TLSv1.2
      - TLSv1.3
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: secret
    key-alias: alias
    key-store-provider: SUN
    client-auth: none
    trust-store: classpath:keystore.p12
    trust-store-password: secret
    trust-store-provider: SUN
    trust-store-type: PKCS12

javamelody:
  enabled: true
  spring-monitoring-enabled: true
  management-endpoint-monitoring-enabled: true